# site
title: Asher Ellis
baseurl: ""
url: "https://asherellis.github.io/"
favicon: "/assets/sample/ico.png"

# bio
header: Asher Ellis
# desc: >
# posts
# date_format: "%Y"
# post_title: thing
# post_date: year
# post_cat: category

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
  - bio.md
  - _drafts
